# Generated by Django 3.1.7 on 2021-07-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0030_alter_answerpaper_user_ip_max_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
