# Generated by Django 3.1.12 on 2021-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0033_auto_20210816_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='incorrect',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
