# Generated by Django 3.2 on 2021-07-19 18:51

from django.db import migrations, models
import yaksh.models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0034_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqtestcase',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_image/', validators=[yaksh.models.validate_image]),
        ),
    ]
