# Generated by Django 3.1.12 on 2021-08-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0034_answerpaper_incorrect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpaper',
            name='incorrect',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='negative_marking',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='negative_score',
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=3.0),
        ),
    ]
