# Generated by Django 3.1.12 on 2021-08-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0035_auto_20210818_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='negative_marks',
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
    ]
