# Generated by Django 3.1.12 on 2021-08-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0037_auto_20210811_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HODProfile',
        ),
    ]
