# Generated by Django 3.1.12 on 2021-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0038_delete_hodprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
