# Generated by Django 3.1.12 on 2021-08-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0033_auto_20210810_1422'),
        ('yaksh', '0041_auto_20210817_1406'),
        ('yaksh', '0037_auto_20210818_0623'),
        ('yaksh', '0041_auto_20210818_0828'),
    ]

    operations = [
    ]
