# Generated by Django 3.1.12 on 2021-08-25 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0042_children_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('ward_user', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Parent',
            new_name='Guardian',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.AddField(
            model_name='ward',
            name='guardian_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.guardian'),
        ),
    ]
