# Generated by Django 3.1.12 on 2021-08-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0042_merge_20210820_0536'),
        ('yaksh', '0043_auto_20210825_1145'),
    ]

    operations = [
    ]
