# Generated by Django 3.1.12 on 2021-09-18 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0045_auto_20210826_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 9, 18, 21, 25, 7, 793492, tzinfo=utc))),
                ('start_time', models.TimeField(default=datetime.datetime(2021, 9, 18, 21, 25, 7, 793555, tzinfo=utc))),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
