# Generated by Django 3.1.12 on 2021-09-18 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0047_auto_20210918_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 18, 21, 58, 16, 131079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 18, 21, 58, 16, 131118, tzinfo=utc)),
        ),
    ]
