# Generated by Django 3.1.12 on 2021-09-18 21:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0048_auto_20210918_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 18, 21, 59, 34, 258522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 18, 21, 59, 34, 258562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendancecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.course'),
        ),
    ]
