# Generated by Django 3.1.12 on 2021-09-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0038_auto_20210914_1509'),
        ('yaksh', '0049_auto_20210918_2159'),
    ]

    operations = [
    ]
