# Generated by Django 3.1.12 on 2021-09-29 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0050_auto_20210929_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 18, 18, 38, 25011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 29, 18, 18, 38, 25070, tzinfo=utc)),
        ),
    ]
