# Generated by Django 3.1.7 on 2021-10-14 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0055_auto_20211011_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_answer_paper',
            name='course_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 14, 8, 23, 13, 314232, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 14, 8, 23, 13, 314232, tzinfo=utc)),
        ),
    ]
