# Generated by Django 3.1.7 on 2021-10-17 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0056_auto_20211014_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 17, 3, 43, 7, 672037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 17, 3, 43, 7, 673037, tzinfo=utc)),
        ),
    ]
