# Generated by Django 3.1.12 on 2021-10-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0058_auto_20211017_1653'),
        ('yaksh', '0052_auto_20210929_1845'),
    ]

    operations = [
    ]
