# Generated by Django 3.1.12 on 2021-10-18 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0059_merge_20211018_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 18, 0, 46, 59018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 18, 0, 46, 59076, tzinfo=utc)),
        ),
    ]
